version: "3"

services:
    app:
        build:
            context: .
        restart: on-failure
        ports:
            - "8000:8000"
        volumes:
          - ./:/app
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: postgres:15-alpine
        container_name: teams_db
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data/
        env_file:
            - .env

volumes:
    db_data:
